package com.gilt.fedex

/**
 * Trait of our generated Soap Client with
 * a standard Async Http Client. This trait can be
 * extended if you want lower level access to functions of the
 * Soap Library.
 *
 * All models and the Soap Client are generated by scalaxb.
 * You can find details about the generated clients usage
 * at http://scalaxb.org/wsdl-support.
 */
trait FedexShipServiceSoapClient
  extends com.fedex.ship.stub.ShipServiceSoapBindings
  with scalaxb.Soap11ClientsAsync
  with scalaxb.DispatchHttpClientsAsync
