// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package com.fedex.ship.stub


import scala.concurrent.Future


trait ShipPortType {
  def processTag(webAuthenticationDetail: com.fedex.ship.stub.WebAuthenticationDetail, clientDetail: com.fedex.ship.stub.ClientDetail, transactionDetail: Option[com.fedex.ship.stub.TransactionDetail], version: com.fedex.ship.stub.VersionId, requestedShipment: com.fedex.ship.stub.RequestedShipment): Future[com.fedex.ship.stub.ProcessTagReply]
  def processShipment(webAuthenticationDetail: com.fedex.ship.stub.WebAuthenticationDetail, clientDetail: com.fedex.ship.stub.ClientDetail, transactionDetail: Option[com.fedex.ship.stub.TransactionDetail], version: com.fedex.ship.stub.VersionId, requestedShipment: com.fedex.ship.stub.RequestedShipment): Future[com.fedex.ship.stub.ProcessShipmentReply]
  def deleteTag(webAuthenticationDetail: com.fedex.ship.stub.WebAuthenticationDetail, clientDetail: com.fedex.ship.stub.ClientDetail, transactionDetail: Option[com.fedex.ship.stub.TransactionDetail], version: com.fedex.ship.stub.VersionId, dispatchLocationId: Option[String], dispatchDate: Option[javax.xml.datatype.XMLGregorianCalendar], payment: com.fedex.ship.stub.Payment, confirmationNumber: String): Future[com.fedex.ship.stub.ShipmentReply]
  def deleteShipment(webAuthenticationDetail: com.fedex.ship.stub.WebAuthenticationDetail, clientDetail: com.fedex.ship.stub.ClientDetail, transactionDetail: Option[com.fedex.ship.stub.TransactionDetail], version: com.fedex.ship.stub.VersionId, shipTimestamp: Option[javax.xml.datatype.XMLGregorianCalendar], trackingId: Option[com.fedex.ship.stub.TrackingId], deletionControl: com.fedex.ship.stub.DeletionControlType): Future[com.fedex.ship.stub.ShipmentReply]
  def validateShipment(webAuthenticationDetail: com.fedex.ship.stub.WebAuthenticationDetail, clientDetail: com.fedex.ship.stub.ClientDetail, transactionDetail: Option[com.fedex.ship.stub.TransactionDetail], version: com.fedex.ship.stub.VersionId, requestedShipment: com.fedex.ship.stub.RequestedShipment): Future[com.fedex.ship.stub.ShipmentReply]
}




